		<table id="editorRow_CKEditor" style="width:inherit;" border="0" cellspacing="0" cellpadding="3">
		  <tr class="row1" style="display: [+display+];">
            <td colspan="2" class="warning" style="color:#707070; background-color:#eeeeee"><h4>[+cke_lang_settings+]<h4></td>
          </tr>
          <tr class="row1" style="display: [+display+];">
            <td nowrap class="warning"><b>[+cke_lang_toolbar_title+]</b></td>
            <td>
            <select name="ck_editor_toolbar" onChange="documentDirty=true;">
            [+toolbarOptions+]
			</select>
			</td>
          </tr>
          <tr class="row1" style="display: [+display+];">
            <td width="200">&nbsp;</td>
            <td class="comment">[+cke_lang_toolbar_message+]</td>
          </tr>
		  <tr class="row1" style="display: [+display+];">
            <td colspan="2"><div class="split"></div></td>
          </tr>
		</table>
